# Generated by Django 4.0.4 on 2022-05-20 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive title of the record.', max_length=256)),
                ('description', models.CharField(blank=True, help_text='Notes abut the object.', max_length=1024, null=True)),
                ('created_ts', models.DateTimeField(default='NOW()')),
                ('updated_ts', models.DateTimeField(default='NOW()')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive title of the record.', max_length=256)),
                ('description', models.CharField(blank=True, help_text='Notes abut the object.', max_length=1024, null=True)),
                ('created_ts', models.DateTimeField(default='NOW()')),
                ('updated_ts', models.DateTimeField(default='NOW()')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive title of the record.', max_length=256)),
                ('description', models.CharField(blank=True, help_text='Notes abut the object.', max_length=1024, null=True)),
                ('created_ts', models.DateTimeField(default='NOW()')),
                ('updated_ts', models.DateTimeField(default='NOW()')),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['name', 'manufacturer', 'license', 'line', 'created_ts'],
            },
        ),
        migrations.CreateModel(
            name='UrlToyModelMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive title of the record.', max_length=256)),
                ('description', models.CharField(blank=True, help_text='Notes abut the object.', max_length=1024, null=True)),
                ('created_ts', models.DateTimeField(default='NOW()')),
                ('updated_ts', models.DateTimeField(default='NOW()')),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name', 'created_ts'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('urltoymodelmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='toys.urltoymodelmixin')),
            ],
            options={
                'abstract': False,
            },
            bases=('toys.urltoymodelmixin',),
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('urltoymodelmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='toys.urltoymodelmixin')),
            ],
            options={
                'abstract': False,
            },
            bases=('toys.urltoymodelmixin',),
        ),
        migrations.AddIndex(
            model_name='urltoymodelmixin',
            index=models.Index(fields=['name'], name='toys_urltoy_name_41e322_idx'),
        ),
        migrations.AddIndex(
            model_name='urltoymodelmixin',
            index=models.Index(fields=['url'], name='toys_urltoy_url_8f4393_idx'),
        ),
        migrations.AddField(
            model_name='toy',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='toys.line'),
        ),
        migrations.AddField(
            model_name='toy',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='toys.scale'),
        ),
        migrations.AddField(
            model_name='toy',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='toys.license'),
        ),
        migrations.AddField(
            model_name='toy',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='toys.manufacturer'),
        ),
        migrations.AddIndex(
            model_name='toy',
            index=models.Index(fields=['name', 'manufacturer', 'license', 'line', 'scale'], name='toys_toy_name_b0fa2a_idx'),
        ),
        migrations.AddIndex(
            model_name='toy',
            index=models.Index(fields=['manufacturer'], name='toys_toy_manufac_4a1b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='toy',
            index=models.Index(fields=['license'], name='toys_toy_license_e9ea15_idx'),
        ),
        migrations.AddIndex(
            model_name='toy',
            index=models.Index(fields=['line'], name='toys_toy_line_id_c66a34_idx'),
        ),
        migrations.AddIndex(
            model_name='toy',
            index=models.Index(fields=['scale'], name='toys_toy_scale_i_811d98_idx'),
        ),
        migrations.AddIndex(
            model_name='toy',
            index=models.Index(fields=['name'], name='toys_toy_name_97dbdb_idx'),
        ),
    ]
