# Generated by Django 4.0.4 on 2022-05-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_alter_line_created_ts_alter_line_updated_ts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='description',
            field=models.TextField(blank=True, help_text='Notes about the object.', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='scale',
            name='description',
            field=models.TextField(blank=True, help_text='Notes about the object.', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='toy',
            name='description',
            field=models.TextField(blank=True, help_text='Notes about the object.', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='urltoymodelmixin',
            name='description',
            field=models.TextField(blank=True, help_text='Notes about the object.', max_length=1024, null=True),
        ),
    ]
