# Generated by Django 4.0.4 on 2022-05-21 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0003_alter_line_description_alter_scale_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='manufacturer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toys.manufacturer'),
        ),
    ]
