# Generated by Django 4.0.4 on 2022-05-21 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0004_line_manufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toy',
            options={'ordering': ['name', 'manufacturer', 'license', 'line', 'wave', 'created_ts']},
        ),
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive title of the record.', max_length=256)),
                ('description', models.TextField(blank=True, help_text='Notes about the object.', max_length=1024, null=True)),
                ('created_ts', models.DateTimeField(blank=True, null=True)),
                ('updated_ts', models.DateTimeField(blank=True, null=True)),
                ('line', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toys.line')),
            ],
            options={
                'ordering': ['name', 'line', 'created_ts'],
            },
        ),
        migrations.AddField(
            model_name='toy',
            name='wave',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toys.wave'),
        ),
        migrations.AddIndex(
            model_name='wave',
            index=models.Index(fields=['name'], name='toys_wave_name_aaef50_idx'),
        ),
        migrations.AddIndex(
            model_name='wave',
            index=models.Index(fields=['line'], name='toys_wave_line_id_49625b_idx'),
        ),
    ]
