# Generated by Django 4.0.4 on 2022-07-04 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0005_alter_toy_options_wave_toy_wave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('credentials', models.TextField(max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'Google Credentials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GoogleSheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sheet_id', models.CharField(max_length=100)),
                ('sheet_range', models.CharField(max_length=100)),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='toys.googlecredentials')),
            ],
            options={
                'verbose_name_plural': 'Google Sheets',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='googlecredentials',
            index=models.Index(fields=['name'], name='toys_google_name_d95a71_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheets',
            index=models.Index(fields=['name'], name='toys_google_name_f4f0ff_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheets',
            index=models.Index(fields=['sheet_id'], name='toys_google_sheet_i_560691_idx'),
        ),
    ]
