# Generated by Django 4.0.4 on 2022-07-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0006_googlecredentials_googlesheets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecredentials',
            name='credentials',
            field=models.TextField(max_length=4096),
        ),
    ]
