# Generated by Django 4.0.4 on 2022-08-29 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0007_alter_googlecredentials_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlesheets',
            name='credentials',
        ),
        migrations.DeleteModel(
            name='GoogleCredentials',
        ),
        migrations.DeleteModel(
            name='GoogleSheets',
        ),
    ]
